LD_FILE = boards/samd51x20-bootloader.ld
USB_VID = 0x04D8
USB_PID = 0xED94
USB_PRODUCT = "PyCubed"
USB_MANUFACTURER = "maholli"

CHIP_VARIANT = SAMD51J20A
CHIP_FAMILY = samd51

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = MPZ

# Not needed.
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_DISPLAYIO = 0
